// <auto-generated />
using Correios.DneBasico.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Correios.DneBasico.Data.Migrations
{
    [DbContext(typeof(DneBasicoDbContext))]
    [Migration("20251217103046_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.Bairro", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("bai_nu");

                    b.Property<int>("LocalidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("loc_nu");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(72)
                        .HasColumnType("character varying(72)")
                        .HasColumnName("bai_no");

                    b.Property<string>("NomeAbreviado")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("bai_no_abrev");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("ufe_sg");

                    b.HasKey("Id");

                    b.HasIndex("LocalidadeId");

                    b.ToTable("bairros", (string)null);
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.CaixaPostalComunitaria", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("cpc_nu");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cep");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cpc_endereco");

                    b.Property<int>("LocalidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("loc_nu");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(72)
                        .HasColumnType("character varying(72)")
                        .HasColumnName("cpc_no");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("ufe_sg");

                    b.HasKey("Id");

                    b.HasIndex("LocalidadeId");

                    b.ToTable("caixas_postais_comunitarias", (string)null);
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.Estado", b =>
                {
                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("ufe_sg");

                    b.Property<string>("Ibge")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("ufe_nu");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)")
                        .HasColumnName("ufe_no");

                    b.HasKey("Uf");

                    b.ToTable("estados", (string)null);
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.FaixaCaixaPostalComunitaria", b =>
                {
                    b.Property<int>("CaixaPostalComunitariaId")
                        .HasColumnType("integer")
                        .HasColumnName("cpc_nu");

                    b.Property<string>("CaixaPostalInicial")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("cpc_inicial");

                    b.Property<string>("CaixaPostalFinal")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("cpc_final");

                    b.HasKey("CaixaPostalComunitariaId", "CaixaPostalInicial");

                    b.ToTable("faixas_caixa_postal_comunitaria", (string)null);
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.FaixaCaixaPostalUop", b =>
                {
                    b.Property<int>("UnidadeOperacionalId")
                        .HasColumnType("integer")
                        .HasColumnName("uop_nu");

                    b.Property<string>("CaixaPostalInicial")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("fnc_inicial");

                    b.Property<string>("CaixaPostalFinal")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("fnc_final");

                    b.HasKey("UnidadeOperacionalId", "CaixaPostalInicial");

                    b.ToTable("faixas_caixa_postal_uop", (string)null);
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.FaixaCepBairro", b =>
                {
                    b.Property<int>("BairroId")
                        .HasColumnType("integer")
                        .HasColumnName("bai_nu");

                    b.Property<string>("CepInicial")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("fcb_cep_ini");

                    b.Property<string>("CepFinal")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("fcb_cep_fim");

                    b.HasKey("BairroId", "CepInicial");

                    b.ToTable("faixas_cep_bairro", (string)null);
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.FaixaCepEstado", b =>
                {
                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("ufe_sg");

                    b.Property<string>("CepInicial")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("ufe_cep_ini");

                    b.Property<string>("CepFinal")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("ufe_cep_fim");

                    b.HasKey("Uf", "CepInicial");

                    b.ToTable("faixas_cep_estado", (string)null);
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.FaixaCepLocalidade", b =>
                {
                    b.Property<int>("LocalidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("loc_nu");

                    b.Property<string>("CepInicial")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("loc_cep_ini");

                    b.Property<int>("TipoFaixa")
                        .HasColumnType("integer")
                        .HasColumnName("loc_tipo_faixa");

                    b.Property<string>("CepFinal")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("loc_cep_fim");

                    b.HasKey("LocalidadeId", "CepInicial", "TipoFaixa");

                    b.ToTable("faixas_cep_localidade", (string)null);
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.FaixaNumericaSeccionamento", b =>
                {
                    b.Property<int>("LogradouroId")
                        .HasColumnType("integer")
                        .HasColumnName("log_nu");

                    b.Property<int>("ParidadeLado")
                        .HasMaxLength(1)
                        .HasColumnType("integer")
                        .HasColumnName("sec_in_lado");

                    b.Property<string>("SeccionamentoFinal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sec_nu_fim");

                    b.Property<string>("SeccionamentoInicial")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sec_nu_ini");

                    b.HasKey("LogradouroId");

                    b.ToTable("faixas_numericas_seccionamento", (string)null);
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.GrandeUsuario", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("gru_nu");

                    b.Property<int>("BairroId")
                        .HasColumnType("integer")
                        .HasColumnName("bai_nu");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cep");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gru_endereco");

                    b.Property<int>("LocalidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("loc_nu");

                    b.Property<int?>("LogradouroId")
                        .HasColumnType("integer")
                        .HasColumnName("log_nu");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(72)
                        .HasColumnType("character varying(72)")
                        .HasColumnName("gru_no");

                    b.Property<string>("NomeAbreviado")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("gru_no_abrev");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("ufe_sg");

                    b.HasKey("Id");

                    b.HasIndex("BairroId");

                    b.HasIndex("LocalidadeId");

                    b.HasIndex("LogradouroId");

                    b.ToTable("grandes_usuarios", (string)null);
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.Localidade", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("loc_nu");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("loc_cep");

                    b.Property<string>("Ibge")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("mun_nu");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(72)
                        .HasColumnType("character varying(72)")
                        .HasColumnName("loc_no");

                    b.Property<string>("NomeAbreviado")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("loc_no_abrev");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("loc_in_sit");

                    b.Property<int?>("SubordinadaId")
                        .HasColumnType("integer")
                        .HasColumnName("loc_nu_sub");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("loc_in_tipo_loc");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("ufe_sg");

                    b.HasKey("Id");

                    b.HasIndex("SubordinadaId");

                    b.HasIndex("Uf");

                    b.ToTable("localidades", (string)null);
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.Logradouro", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("log_nu");

                    b.Property<int>("BairroId")
                        .HasColumnType("integer")
                        .HasColumnName("bai_nu_ini");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cep");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("log_complemento");

                    b.Property<int>("LocalidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("loc_nu");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("log_no");

                    b.Property<string>("NomeAbreviado")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("log_no_abrev");

                    b.Property<string>("StatusTipo")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("log_sta_tlo");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("tlo_tx");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("ufe_sg");

                    b.HasKey("Id");

                    b.HasIndex("BairroId");

                    b.HasIndex("LocalidadeId");

                    b.ToTable("logradouros", (string)null);
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.Pais", b =>
                {
                    b.Property<string>("Sigla")
                        .HasColumnType("text")
                        .HasColumnName("pai_sg");

                    b.Property<string>("Abreviatura")
                        .HasColumnType("text")
                        .HasColumnName("pai_abreviatura");

                    b.Property<string>("NomeFrances")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pai_no_frances");

                    b.Property<string>("NomeIngles")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pai_no_ingles");

                    b.Property<string>("NomePortugues")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pai_no_portugues");

                    b.Property<string>("SiglaAlternativa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pai_sg_alternativa");

                    b.HasKey("Sigla");

                    b.ToTable("paises", (string)null);
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.UnidadeOperacional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("uop_nu");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BairroId")
                        .HasColumnType("integer")
                        .HasColumnName("bai_nu");

                    b.Property<string>("CaixasPostais")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("uop_in_cp");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cep");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("uop_endereco");

                    b.Property<int>("LocalidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("loc_nu");

                    b.Property<int?>("LogradouroId")
                        .HasColumnType("integer")
                        .HasColumnName("log_nu");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("uop_no");

                    b.Property<string>("NomeAbreviado")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("uop_no_abrev");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("ufe_sg");

                    b.HasKey("Id");

                    b.HasIndex("BairroId");

                    b.HasIndex("LocalidadeId");

                    b.HasIndex("LogradouroId");

                    b.HasIndex("Uf");

                    b.ToTable("unidades_operacionais", (string)null);
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.VariacaoBairro", b =>
                {
                    b.Property<int>("BairroId")
                        .HasColumnType("integer")
                        .HasColumnName("bai_nu");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("vdb_nu");

                    b.Property<string>("Denominacao")
                        .IsRequired()
                        .HasMaxLength(72)
                        .HasColumnType("character varying(72)")
                        .HasColumnName("vdb_tx");

                    b.HasKey("BairroId", "Ordem");

                    b.ToTable("variacoes_bairro", (string)null);
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.VariacaoLocalidade", b =>
                {
                    b.Property<int>("LocalidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("loc_nu");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("val_nu");

                    b.Property<string>("Denominacao")
                        .IsRequired()
                        .HasMaxLength(72)
                        .HasColumnType("character varying(72)")
                        .HasColumnName("val_tx");

                    b.HasKey("LocalidadeId", "Ordem");

                    b.ToTable("variacoes_localidade", (string)null);
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.VariacaoLogradouro", b =>
                {
                    b.Property<int>("LogradouroId")
                        .HasColumnType("integer")
                        .HasColumnName("log_nu");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("vlo_nu");

                    b.Property<string>("Denominacao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("vlo_tx");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("tlo_tx");

                    b.HasKey("LogradouroId", "Ordem");

                    b.ToTable("variacoes_logradouro", (string)null);
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.Bairro", b =>
                {
                    b.HasOne("Correios.DneBasico.Domain.Entities.Localidade", "Localidade")
                        .WithMany()
                        .HasForeignKey("LocalidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localidade");
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.CaixaPostalComunitaria", b =>
                {
                    b.HasOne("Correios.DneBasico.Domain.Entities.Localidade", "Localidade")
                        .WithMany()
                        .HasForeignKey("LocalidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localidade");
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.FaixaCaixaPostalComunitaria", b =>
                {
                    b.HasOne("Correios.DneBasico.Domain.Entities.CaixaPostalComunitaria", "CaixaPostalComunitaria")
                        .WithMany("Faixas")
                        .HasForeignKey("CaixaPostalComunitariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaixaPostalComunitaria");
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.FaixaCaixaPostalUop", b =>
                {
                    b.HasOne("Correios.DneBasico.Domain.Entities.UnidadeOperacional", "UnidadeOperacional")
                        .WithMany("FaixasCaixaPostal")
                        .HasForeignKey("UnidadeOperacionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadeOperacional");
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.FaixaCepBairro", b =>
                {
                    b.HasOne("Correios.DneBasico.Domain.Entities.Bairro", "Bairro")
                        .WithMany()
                        .HasForeignKey("BairroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bairro");
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.FaixaCepEstado", b =>
                {
                    b.HasOne("Correios.DneBasico.Domain.Entities.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("Uf")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.FaixaCepLocalidade", b =>
                {
                    b.HasOne("Correios.DneBasico.Domain.Entities.Localidade", "Localidade")
                        .WithMany()
                        .HasForeignKey("LocalidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localidade");
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.FaixaNumericaSeccionamento", b =>
                {
                    b.HasOne("Correios.DneBasico.Domain.Entities.Logradouro", "Logradouro")
                        .WithOne()
                        .HasForeignKey("Correios.DneBasico.Domain.Entities.FaixaNumericaSeccionamento", "LogradouroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Logradouro");
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.GrandeUsuario", b =>
                {
                    b.HasOne("Correios.DneBasico.Domain.Entities.Bairro", "Bairro")
                        .WithMany()
                        .HasForeignKey("BairroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Correios.DneBasico.Domain.Entities.Localidade", "Localidade")
                        .WithMany()
                        .HasForeignKey("LocalidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Correios.DneBasico.Domain.Entities.Logradouro", "Logradouro")
                        .WithMany()
                        .HasForeignKey("LogradouroId");

                    b.Navigation("Bairro");

                    b.Navigation("Localidade");

                    b.Navigation("Logradouro");
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.Localidade", b =>
                {
                    b.HasOne("Correios.DneBasico.Domain.Entities.Localidade", "Subordinada")
                        .WithMany()
                        .HasForeignKey("SubordinadaId");

                    b.HasOne("Correios.DneBasico.Domain.Entities.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("Uf")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Subordinada");
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.Logradouro", b =>
                {
                    b.HasOne("Correios.DneBasico.Domain.Entities.Bairro", "Bairro")
                        .WithMany()
                        .HasForeignKey("BairroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Correios.DneBasico.Domain.Entities.Localidade", "Localidade")
                        .WithMany()
                        .HasForeignKey("LocalidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bairro");

                    b.Navigation("Localidade");
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.UnidadeOperacional", b =>
                {
                    b.HasOne("Correios.DneBasico.Domain.Entities.Bairro", "Bairro")
                        .WithMany()
                        .HasForeignKey("BairroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Correios.DneBasico.Domain.Entities.Localidade", "Localidade")
                        .WithMany()
                        .HasForeignKey("LocalidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Correios.DneBasico.Domain.Entities.Logradouro", "Logradouro")
                        .WithMany()
                        .HasForeignKey("LogradouroId");

                    b.HasOne("Correios.DneBasico.Domain.Entities.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("Uf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bairro");

                    b.Navigation("Estado");

                    b.Navigation("Localidade");

                    b.Navigation("Logradouro");
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.VariacaoBairro", b =>
                {
                    b.HasOne("Correios.DneBasico.Domain.Entities.Bairro", "Bairro")
                        .WithMany("Variacoes")
                        .HasForeignKey("BairroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bairro");
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.VariacaoLocalidade", b =>
                {
                    b.HasOne("Correios.DneBasico.Domain.Entities.Localidade", "Localidade")
                        .WithMany("Variacoes")
                        .HasForeignKey("LocalidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localidade");
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.VariacaoLogradouro", b =>
                {
                    b.HasOne("Correios.DneBasico.Domain.Entities.Logradouro", "Logradouro")
                        .WithMany("Variacoes")
                        .HasForeignKey("LogradouroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logradouro");
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.Bairro", b =>
                {
                    b.Navigation("Variacoes");
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.CaixaPostalComunitaria", b =>
                {
                    b.Navigation("Faixas");
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.Localidade", b =>
                {
                    b.Navigation("Variacoes");
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.Logradouro", b =>
                {
                    b.Navigation("Variacoes");
                });

            modelBuilder.Entity("Correios.DneBasico.Domain.Entities.UnidadeOperacional", b =>
                {
                    b.Navigation("FaixasCaixaPostal");
                });
#pragma warning restore 612, 618
        }
    }
}
